name: jawnnypoo
description: Website for me

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.1.0
  font_awesome_flutter: ^10.1.0
  flutter_markdown: ^0.6.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/firacode-bold.ttf
