name: jawnnypoo
description: Website for me

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  url_launcher: ^6.1.0
  font_awesome_flutter: ^10.1.0
  carousel_slider: ^4.2.0
  flutter_markdown: ^0.6.13
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/instacart_1.png
    - assets/images/
    - assets/json/

  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/firacode-bold.ttf
